cbproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView, LogoutView




urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='quotes/login.html')),
	path('logout/', LogoutView.as_view(next_page='/')),
    path('', include('quotes.urls')),
]

quotes/urls.py
from django.urls import path

from . import views

app_name ='quotes'
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
    # ex: /5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

quotes/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    comment_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_text

quotes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice, Comment
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from jinja2 import Template #remove this.

@login_required
@csrf_exempt #remove this 
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'quotes/index.html', context)

#@login_required <- broken access control, add this to fix
@csrf_exempt
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'quotes/detail.html', {'question': question})

#@login_required <- broken access control, add this to fix
@csrf_exempt
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    comments = Comment.objects.filter(question=question)
    return render(request, 'quotes/results.html', {'question': question, 'comments': comments})
    
#@login_required <- broken access control, add this to fix
@csrf_exempt
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        comment = request.POST.get("comment")
        print(comment)
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'quotes/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        comment_text = request.POST.get("comment", "")
        
        if comment_text.strip():
            template = Template(comment_text)
            jinja_comment = template.render()
            Comment.objects.create(question=question, comment_text=jinja_comment)
            #remove the 3 lines above, replace with this:
            #Comment.objects.create(question=question, comment_text=comment_text)

        selected_choice.votes += 1
        selected_choice.save()
        
        return HttpResponseRedirect(reverse('quotes:results', args=(question.id,)))

quotes/templates/quotes/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>VoteQuote</title>
  </head>
  <body>
    <main>
      <h1>VoteQuote</h1>  
      <h2>{{ question.question_text }}</h2>
    </main>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'quotes:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
      {% endfor %}
      <p>Other comments?</p>
      <input type="text" id="comment" name="comment"><br>
      <input type="submit" value="Vote">
    </form>
    <a href="{% url 'quotes:index' %}">Front Page</a>
  </body>
</html>

quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>VoteQuote</title> 
  </head>
  <body>
    <main>
        <h1>VoteQuote</h1>  
    </main>
    <p>Choose a quote to vote on!</p>
    {% if latest_question_list %}
      <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'quotes:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No quotes are available.</p>
    {% endif %}
    <form id="logout-form" method="post" action="/logout/">
      {% csrf_token %}
      <input type="hidden">
      <button type="submit">Log out</button>
    </form>
    <!-- remove link to admin page and text that provides login information-->
    <a href="admin">Admin</a>
    <p style="color:white;">For developers: username: admin, password: cybersec1</p>
  </body>
</html>

quotes/templates/quotes/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>VoteQuote</title>
  </head>
  <body>
    <h2>Login</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Login</button>
    </form>    
  </body>
</html>

quotes/templates/quotes/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>VoteQuote</title>
  </head>
  <body>
    <main>
        <h1>VoteQuote</h1>  
    </main>
    <h2>{{ question.question_text }}</h2>
    <ul>
      {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
      {% endfor %}
    </ul>
    <h3>Other comments:</h3>
    <ul>
        <!-- Remove |safe from the comment displaying line. Flaw: Injection (XSS)-->
        {% for comment in comments %}
          <li>{{ comment.comment_text|safe }}</li>
          {% empty %}
          <li>No one has given a comment, yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'quotes:detail' question.id %}">Vote again?</a>
    <a href="{% url 'quotes:index' %}">Front Page</a>
  </body>
</html>